default:
  image: registry.access.redhat.com/ubi8/python-38


before_script:
  - pip install flake8
  - pip freeze
  - bash --version
  - python --version

stages:
  - test

build:
  stage: test
  tags:
    - shared
  script:
    - find . -iname "*.sh" | xargs bash -x -n
    - find . -iname "*.py" | xargs flake8
    - find . -iname "*.js" | xargs node --check

